# Site settings
title: DSC180_Methodology_5
author:
  name: Jinxin Xiao
  email: j5xia@ucsd.edu
description: "."

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 
